name: hackenza
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch
  - pytorch::torchvision
  - numpy
  - pandas
  - scikit-learn
  - pip:
    - torchvision
